### ISSUE TITLE
Allow endpoint security to be disabled

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#10]
This ~~requires~~ compliments https://github.com/infinispan/infinispan-images/issues/16

We should then allow the following yaml to be configured to disable auth on specifc endpoints:

```yaml
endpoints:
  hotrod:
    auth: true | false
    enabled: true
  rest:
    auth: true | false
    enabled: true
```

**Comment by dev-e** [comment]
@ryanemerson , I have tried to disable auth with this config, but the server still requires authentication.
Minimal reproducible configuration:
Infinispan: `11.0.3.Final`
Do not pass `IDENTITIES_PATH`, `USER` and `PASS` variables
infinispan.yaml:
```
...
endpoints:
  hotrod:
    auth: false
    enabled: true
    qop: auth
    serverName: infinispan
  rest:
    auth: false
    enabled: true
...
```
Then `curl -iv infinispan:11222/rest/v2/caches`: `HTTP/1.1 401 Unauthorized`
When using auto-generated credentials from this setup, the request authenticated.
