### ISSUE TITLE
Add clustered locks configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#102]
It should be possible to configure the num-owners and reliability for clustered locks via yaml:

```yaml
infinispan:
  locks:
    owners: 2
    reliability: available
```
