### ISSUE TITLE
XSite replication not working

### ISSUE THREAD

**Issue by shivan** [infinispan/infinispan-images#106]
Hi,

I tried XSite replication on a local docker.

Config1 (using port 7300):
```
jgroups:
  diagnostics: true
  encrypt: false
xsite:
  transport: tunnel
  address: 10.35.50.133
  name: NYC
  port: 7300
  backups:
    - address: 10.35.50.133
      name: LON
      port: 7200
logging:
  console:
    level: debug
```

Config 2 (using port 7200):
```
jgroups:
  diagnostics: true
  encrypt: false
xsite:
  transport: tunnel
  address: 10.35.50.133
  name: LON
  port: 7200
  backups:
    - address: 10.35.50.133
      name: NYC
      port: 7300
logging:
  console:
    level: debug
```

My Docker-Commands:

`docker run --rm -p 11222:11222 -p 7300:7300 -v c:/work/InfiniSpan:/user-config --name infinispan1 -e IDENTITIES_PATH="/user-config/identities.yaml" -e CONFIG_PATH="/user-config/config1.yaml" --network bridge infinispan/server:11.0.4.Final-2
`

`docker run --rm -p 12222:11222 -p 7200:7300 -v c:/work/InfiniSpan:/user-config --name infinispan2 -e IDENTITIES_PATH="/user-config/identities.yaml" -e CONFIG_PATH="/user-config/config2.yaml" --network Bridge2  infinispan/server:11.0.4.Final-2
`

But when I create a new REPL_SYNC Cache on one of them, it won't be created on the other one automatically.
It only works when both are on the same network, but then they communicate through Multicast instead of XSite.

Is this docker container really working with XSite?
