### ISSUE TITLE
Yaml Configuration for caches definition

### ISSUE THREAD

**Issue by waltari2001** [infinispan/infinispan-images#129]
Hi,

I am trying to include custom caches in the infinispan.xml file via the YAML config. It's not quite clear how things get translated.

```
<cache-container>
  <replicated-cache name="work" statistics="true">
    <backups>
      <backup site="LON" strategy="SYNC"/>
    </backups>
  </replicated-cache>
  <replicated-cache name="sessions" statistics="true">
    <backups>
      <backup site="LON" strategy="SYNC"/>
    </backups>
  </replicated-cache>
</cache-container>
```

I have tried 

```
infinispan:
  cache-container:
    - replicated-cache:
      name: work
      statistics: true
      backups:
      - backup:
        site: LON
        strategy: SYNC
...
...
```

But it didn't take. Any help is appreciated !

**Comment by ryanemerson** [comment]
@waltari2001 It's not possible to define cache configurations in the image yaml file atm. You can use one of our clients (CLI, Web console, REST endpoint etc) to populate these at runtime, or you can use a custom configuration with the  image following [these steps](https://github.com/infinispan/infinispan-images#custom-infinispan-xml-configuration)

**Comment by ryanemerson** [comment]
From Infinispan 13.x it's possible to provide the entire server configuration, including static cache definitions, via yaml: https://github.com/infinispan/infinispan-images#server-configuration

**Comment by pkrawiec-advanced** [comment]
Is there any guide about how to setup multiple caches? I have tried with:
```
infinispan:
  cacheContainer:
    distributedCache:
    - capacityFactor: "1.0"
      encoding:
        mediaType: application/x-protostream
      expiration:
        lifespan: "5000"
        maxIdle: "1000"
      memory:
        maxCount: "1000000"
        whenFull: REMOVE
      mode: SYNC
      name: offlineSessions
      owners: "2"
      partitionHandling:
        mergePolicy: PREFERRED_NON_NULL
        whenSplit: ALLOW_READ_WRITES
      segments: "256"
      statistics: "true"
    - capacityFactor: "1.0"
      encoding:
        mediaType: application/x-protostream
      expiration:
        lifespan: "5000"
        maxIdle: "1000"
      memory:
        maxCount: "1000000"
        whenFull: REMOVE
      mode: SYNC
      name: loginFailures
      owners: "2"
      partitionHandling:
        mergePolicy: PREFERRED_NON_NULL
        whenSplit: ALLOW_READ_WRITES
      segments: "256"
      statistics: "true"
    name: default
    security:
      authorization: {}
    transport:
      cluster: ${infinispan.cluster.name:cluster}
      node-name: ${infinispan.node.name:}
      stack: kubernetes
  server:
    endpoints:
    - securityRealm: default
      socketBinding: default
    - connectors:
        rest:
          restConnector:
            authentication:
              mechanisms: BASIC
      securityRealm: metrics
      socketBinding: metrics
    interfaces:
    - inetAddress:
        value: ${infinispan.bind.address:127.0.0.1}
      name: public
    security:
      credentialStores:
      - clearTextCredential:
          clearText: secret
        name: credentials
        path: credentials.pfx
      securityRealms:
      - name: default
        propertiesRealm:
          groupProperties:
            path: groups.properties
          groupsAttribute: Roles
          userProperties:
            path: users.properties
      - name: metrics
        propertiesRealm:
          groupProperties:
            path: metrics-groups.properties
            relativeTo: infinispan.server.config.path
          groupsAttribute: Roles
          userProperties:
            path: metrics-users.properties
            relativeTo: infinispan.server.config.path
    socketBindings:
      defaultInterface: public
      portOffset: ${infinispan.socket.binding.port-offset:0}
      socketBinding:
      - name: default
        port: 11222
      - name: metrics
        port: 11223
```
but I am getting:
![image](https://user-images.githubusercontent.com/59048838/153585945-0e31cee7-632e-417c-a64b-73232e7b5825.png)

It works with a single `distributedCache` element (not a list)

Using:
quay.io/infinispan/server:13.0
