### ISSUE TITLE
Enable CORS configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#23]
https://infinispan.org/docs/stable/titles/rest/rest.html#rest_server_cors

Suggested format:

```yaml
endpoints:
  rest:
    auth: true
    enabled: true
    cors:
      - name: restrict-host1
        allowCredentials: false
        origins:
          - http://host1
          - https://host1
        methods:
          - GET
      - name: allow all
        allowCredentials: true
        origins:
          - '*'
        methods:
          - GET
          - OPTIONS
          - POST
          - PUT
          - DELETE
        exposeHeaders:
          - Key-Content-Type
        maxAgeSeconds: 1
        
```
