### ISSUE TITLE
Enable User Marshaller Configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#24]
It should be possible for a custom user marshaller and the class white list to be configured via the config yaml file. This is necessary to facilitate storing of objects in the server as `application/x-java-object`.

Possiblle yaml config:

```yaml
infinispan:
  marshaller: org.infinispan.commons.marshall.JavaSerializationMarshaller
  whiteListRegex: ""
```
