### ISSUE TITLE
Remove Probe Implementations

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#29]
The check to see if the cluster is HEALTHY in the readiness probe doesn't make sense, because if the cluster becomes DEGRADED then the server(s) would be killed and consequently date would be lost.

If the server is able to handle REST requests then it is both live & ready. Therefore, we should remove our custom probe implementations and utilise the kubernetes `httpGet` probes.
```yaml
        livenessProbe:
          httpGet:
            path: /rest/v2/cache-managers/clustered/health/status
            port: infinispan
        readinessProbe:
          httpGet:
            path: /rest/v2/cache-managers/clustered/health/status
            port: infinispan
```

@rigazilla Can you update the operator yaml to utilise `httpGet` and verify that this functions at expected?
