### ISSUE TITLE
Allow logging configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#3]
It should be possible for users to configure logging via the config yaml in the following format:

```yaml
logging:
  console:
    level: trace
    pattern: '%K{level}%d{HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%e%n'
  file:
    level: trace
    path: server/log
    pattern: '%d{yyyy-MM-dd HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%e%n'
  categories:
    com.arjuna: warn
    org.infinispan: info
    org.jgroups: warn
```
