### ISSUE TITLE
Add support for configuring Hotrod & Rest access log files

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#47]
Currently our logging support only works for the `server.log` file and console output. If `org.infinispan.REST_ACCESS_LOG` is specified, then the logs will always appear in `server.log`, however we should detect when this category is specified and ensure that the REST-ACCESS-FILE is used instead.

```yaml
logging:
  categories:
    org.infinispan: info
    org.infinispan.HOTROD_ACCESS_LOG: trace
    org.infinispan.REST_ACCESS_LOG: trace
```
Should result in the `server/log/rest-access.log` and `server/log/hotrod-access.log` being used.
