### ISSUE TITLE
Add authorization configuration

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#57]
It should be possible to add server authorization configuration via the `server.yaml`.

```yaml
security:
  authorization:
    roles:
      - name: vassal
        permissions:
          - READ
          - WRITE
          - LISTEN
      - name: peasent
        permissions:
          - READ
```

Which will result in the following xml:

```xml
         <authorization>
            <identity-role-mapper/>
            <role name="peasant" permissions="READ"/>
            <role name="vassal" permissions="READ WRITE LISTEN"/>
         </authorization>
```
